export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_FORM_EDIT = "USER_FORM_EDIT";
export const UPDATE_CURRENT_USER_DETAILS = "UPDATE_CURRENT_USER_DETAILS"